//File code generated using T4 Template found in the project: Abm.Pyro.CodeGeneration
// Last Generated : 19/11/2024 5:45:22 PM

using Abm.Pyro.Domain.Model;
namespace Abm.Pyro.Repository.Seed;

public static class SearchParameterStoreComponentSeed
{
  public static IEnumerable<SearchParameterStoreComponent> Get()
  {
    return new List<SearchParameterStoreComponent>() 
           {
                  new SearchParameterStoreComponent(1, 34, new Uri("http://hl7.org/fhir/SearchParameter/ActivityDefinition-context-type"), "code"),
                new SearchParameterStoreComponent(2, 34, new Uri("http://hl7.org/fhir/SearchParameter/ActivityDefinition-context-quantity"), "value.as(Quantity) | value.as(Range)"),
                new SearchParameterStoreComponent(3, 35, new Uri("http://hl7.org/fhir/SearchParameter/ActivityDefinition-context-type"), "code"),
                new SearchParameterStoreComponent(4, 35, new Uri("http://hl7.org/fhir/SearchParameter/ActivityDefinition-context"), "value.as(CodeableConcept)"),
                new SearchParameterStoreComponent(5, 142, new Uri("http://hl7.org/fhir/SearchParameter/conformance-context-type"), "code"),
                new SearchParameterStoreComponent(6, 142, new Uri("http://hl7.org/fhir/SearchParameter/conformance-context-quantity"), "value.as(Quantity) | value.as(Range)"),
                new SearchParameterStoreComponent(7, 143, new Uri("http://hl7.org/fhir/SearchParameter/conformance-context-type"), "code"),
                new SearchParameterStoreComponent(8, 143, new Uri("http://hl7.org/fhir/SearchParameter/conformance-context"), "value.as(CodeableConcept)"),
                new SearchParameterStoreComponent(9, 196, new Uri("http://hl7.org/fhir/SearchParameter/ChargeItemDefinition-context-type"), "code"),
                new SearchParameterStoreComponent(10, 196, new Uri("http://hl7.org/fhir/SearchParameter/ChargeItemDefinition-context-quantity"), "value.as(Quantity) | value.as(Range)"),
                new SearchParameterStoreComponent(11, 197, new Uri("http://hl7.org/fhir/SearchParameter/ChargeItemDefinition-context-type"), "code"),
                new SearchParameterStoreComponent(12, 197, new Uri("http://hl7.org/fhir/SearchParameter/ChargeItemDefinition-context"), "value.as(CodeableConcept)"),
                new SearchParameterStoreComponent(13, 450, new Uri("http://hl7.org/fhir/SearchParameter/DocumentReference-relatesto"), "code"),
                new SearchParameterStoreComponent(14, 450, new Uri("http://hl7.org/fhir/SearchParameter/DocumentReference-relation"), "target"),
                new SearchParameterStoreComponent(15, 465, new Uri("http://hl7.org/fhir/SearchParameter/EffectEvidenceSynthesis-context-type"), "code"),
                new SearchParameterStoreComponent(16, 465, new Uri("http://hl7.org/fhir/SearchParameter/EffectEvidenceSynthesis-context-quantity"), "value.as(Quantity) | value.as(Range)"),
                new SearchParameterStoreComponent(17, 466, new Uri("http://hl7.org/fhir/SearchParameter/EffectEvidenceSynthesis-context-type"), "code"),
                new SearchParameterStoreComponent(18, 466, new Uri("http://hl7.org/fhir/SearchParameter/EffectEvidenceSynthesis-context"), "value.as(CodeableConcept)"),
                new SearchParameterStoreComponent(19, 524, new Uri("http://hl7.org/fhir/SearchParameter/EventDefinition-context-type"), "code"),
                new SearchParameterStoreComponent(20, 524, new Uri("http://hl7.org/fhir/SearchParameter/EventDefinition-context-quantity"), "value.as(Quantity) | value.as(Range)"),
                new SearchParameterStoreComponent(21, 525, new Uri("http://hl7.org/fhir/SearchParameter/EventDefinition-context-type"), "code"),
                new SearchParameterStoreComponent(22, 525, new Uri("http://hl7.org/fhir/SearchParameter/EventDefinition-context"), "value.as(CodeableConcept)"),
                new SearchParameterStoreComponent(23, 546, new Uri("http://hl7.org/fhir/SearchParameter/Evidence-context-type"), "code"),
                new SearchParameterStoreComponent(24, 546, new Uri("http://hl7.org/fhir/SearchParameter/Evidence-context-quantity"), "value.as(Quantity) | value.as(Range)"),
                new SearchParameterStoreComponent(25, 547, new Uri("http://hl7.org/fhir/SearchParameter/Evidence-context-type"), "code"),
                new SearchParameterStoreComponent(26, 547, new Uri("http://hl7.org/fhir/SearchParameter/Evidence-context"), "value.as(CodeableConcept)"),
                new SearchParameterStoreComponent(27, 568, new Uri("http://hl7.org/fhir/SearchParameter/EvidenceVariable-context-type"), "code"),
                new SearchParameterStoreComponent(28, 568, new Uri("http://hl7.org/fhir/SearchParameter/EvidenceVariable-context-quantity"), "value.as(Quantity) | value.as(Range)"),
                new SearchParameterStoreComponent(29, 569, new Uri("http://hl7.org/fhir/SearchParameter/EvidenceVariable-context-type"), "code"),
                new SearchParameterStoreComponent(30, 569, new Uri("http://hl7.org/fhir/SearchParameter/EvidenceVariable-context"), "value.as(CodeableConcept)"),
                new SearchParameterStoreComponent(31, 581, new Uri("http://hl7.org/fhir/SearchParameter/ExampleScenario-context-type"), "code"),
                new SearchParameterStoreComponent(32, 581, new Uri("http://hl7.org/fhir/SearchParameter/ExampleScenario-context-quantity"), "value.as(Quantity) | value.as(Range)"),
                new SearchParameterStoreComponent(33, 582, new Uri("http://hl7.org/fhir/SearchParameter/ExampleScenario-context-type"), "code"),
                new SearchParameterStoreComponent(34, 582, new Uri("http://hl7.org/fhir/SearchParameter/ExampleScenario-context"), "value.as(CodeableConcept)"),
                new SearchParameterStoreComponent(35, 624, new Uri("http://hl7.org/fhir/SearchParameter/Group-characteristic"), "code"),
                new SearchParameterStoreComponent(36, 624, new Uri("http://hl7.org/fhir/SearchParameter/Group-value"), "value"),
                new SearchParameterStoreComponent(37, 737, new Uri("http://hl7.org/fhir/SearchParameter/Library-context-type"), "code"),
                new SearchParameterStoreComponent(38, 737, new Uri("http://hl7.org/fhir/SearchParameter/Library-context-quantity"), "value.as(Quantity) | value.as(Range)"),
                new SearchParameterStoreComponent(39, 738, new Uri("http://hl7.org/fhir/SearchParameter/Library-context-type"), "code"),
                new SearchParameterStoreComponent(40, 738, new Uri("http://hl7.org/fhir/SearchParameter/Library-context"), "value.as(CodeableConcept)"),
                new SearchParameterStoreComponent(41, 784, new Uri("http://hl7.org/fhir/SearchParameter/Measure-context-type"), "code"),
                new SearchParameterStoreComponent(42, 784, new Uri("http://hl7.org/fhir/SearchParameter/Measure-context-quantity"), "value.as(Quantity) | value.as(Range)"),
                new SearchParameterStoreComponent(43, 785, new Uri("http://hl7.org/fhir/SearchParameter/Measure-context-type"), "code"),
                new SearchParameterStoreComponent(44, 785, new Uri("http://hl7.org/fhir/SearchParameter/Measure-context"), "value.as(CodeableConcept)"),
                new SearchParameterStoreComponent(45, 910, new Uri("http://hl7.org/fhir/SearchParameter/MolecularSequence-chromosome"), "%resource.referenceSeq.chromosome"),
                new SearchParameterStoreComponent(46, 910, new Uri("http://hl7.org/fhir/SearchParameter/MolecularSequence-variant-start"), "start"),
                new SearchParameterStoreComponent(47, 910, new Uri("http://hl7.org/fhir/SearchParameter/MolecularSequence-variant-end"), "end"),
                new SearchParameterStoreComponent(48, 911, new Uri("http://hl7.org/fhir/SearchParameter/MolecularSequence-chromosome"), "chromosome"),
                new SearchParameterStoreComponent(49, 911, new Uri("http://hl7.org/fhir/SearchParameter/MolecularSequence-window-start"), "windowStart"),
                new SearchParameterStoreComponent(50, 911, new Uri("http://hl7.org/fhir/SearchParameter/MolecularSequence-window-end"), "windowEnd"),
                new SearchParameterStoreComponent(51, 912, new Uri("http://hl7.org/fhir/SearchParameter/MolecularSequence-referenceseqid"), "%resource.referenceSeq.referenceSeqId"),
                new SearchParameterStoreComponent(52, 912, new Uri("http://hl7.org/fhir/SearchParameter/MolecularSequence-variant-start"), "start"),
                new SearchParameterStoreComponent(53, 912, new Uri("http://hl7.org/fhir/SearchParameter/MolecularSequence-variant-end"), "end"),
                new SearchParameterStoreComponent(54, 913, new Uri("http://hl7.org/fhir/SearchParameter/MolecularSequence-referenceseqid"), "referenceSeqId"),
                new SearchParameterStoreComponent(55, 913, new Uri("http://hl7.org/fhir/SearchParameter/MolecularSequence-window-start"), "windowStart"),
                new SearchParameterStoreComponent(56, 913, new Uri("http://hl7.org/fhir/SearchParameter/MolecularSequence-window-end"), "windowEnd"),
                new SearchParameterStoreComponent(57, 956, new Uri("http://hl7.org/fhir/SearchParameter/clinical-code"), "code"),
                new SearchParameterStoreComponent(58, 956, new Uri("http://hl7.org/fhir/SearchParameter/Observation-value-concept"), "value.as(CodeableConcept)"),
                new SearchParameterStoreComponent(59, 957, new Uri("http://hl7.org/fhir/SearchParameter/clinical-code"), "code"),
                new SearchParameterStoreComponent(60, 957, new Uri("http://hl7.org/fhir/SearchParameter/Observation-value-date"), "value.as(DateTime) | value.as(Period)"),
                new SearchParameterStoreComponent(61, 958, new Uri("http://hl7.org/fhir/SearchParameter/clinical-code"), "code"),
                new SearchParameterStoreComponent(62, 958, new Uri("http://hl7.org/fhir/SearchParameter/Observation-value-quantity"), "value.as(Quantity)"),
                new SearchParameterStoreComponent(63, 959, new Uri("http://hl7.org/fhir/SearchParameter/clinical-code"), "code"),
                new SearchParameterStoreComponent(64, 959, new Uri("http://hl7.org/fhir/SearchParameter/Observation-value-string"), "value.as(string)"),
                new SearchParameterStoreComponent(65, 960, new Uri("http://hl7.org/fhir/SearchParameter/Observation-combo-code"), "code"),
                new SearchParameterStoreComponent(66, 960, new Uri("http://hl7.org/fhir/SearchParameter/Observation-combo-value-concept"), "value.as(CodeableConcept)"),
                new SearchParameterStoreComponent(67, 961, new Uri("http://hl7.org/fhir/SearchParameter/Observation-combo-code"), "code"),
                new SearchParameterStoreComponent(68, 961, new Uri("http://hl7.org/fhir/SearchParameter/Observation-combo-value-quantity"), "value.as(Quantity)"),
                new SearchParameterStoreComponent(69, 962, new Uri("http://hl7.org/fhir/SearchParameter/Observation-component-code"), "code"),
                new SearchParameterStoreComponent(70, 962, new Uri("http://hl7.org/fhir/SearchParameter/Observation-component-value-concept"), "value.as(CodeableConcept)"),
                new SearchParameterStoreComponent(71, 963, new Uri("http://hl7.org/fhir/SearchParameter/Observation-component-code"), "code"),
                new SearchParameterStoreComponent(72, 963, new Uri("http://hl7.org/fhir/SearchParameter/Observation-component-value-quantity"), "value.as(Quantity)"),
                new SearchParameterStoreComponent(73, 1066, new Uri("http://hl7.org/fhir/SearchParameter/PlanDefinition-context-type"), "code"),
                new SearchParameterStoreComponent(74, 1066, new Uri("http://hl7.org/fhir/SearchParameter/PlanDefinition-context-quantity"), "value.as(Quantity) | value.as(Range)"),
                new SearchParameterStoreComponent(75, 1067, new Uri("http://hl7.org/fhir/SearchParameter/PlanDefinition-context-type"), "code"),
                new SearchParameterStoreComponent(76, 1067, new Uri("http://hl7.org/fhir/SearchParameter/PlanDefinition-context"), "value.as(CodeableConcept)"),
                new SearchParameterStoreComponent(77, 1120, new Uri("http://hl7.org/fhir/SearchParameter/Questionnaire-context-type"), "code"),
                new SearchParameterStoreComponent(78, 1120, new Uri("http://hl7.org/fhir/SearchParameter/Questionnaire-context-quantity"), "value.as(Quantity) | value.as(Range)"),
                new SearchParameterStoreComponent(79, 1121, new Uri("http://hl7.org/fhir/SearchParameter/Questionnaire-context-type"), "code"),
                new SearchParameterStoreComponent(80, 1121, new Uri("http://hl7.org/fhir/SearchParameter/Questionnaire-context"), "value.as(CodeableConcept)"),
                new SearchParameterStoreComponent(81, 1172, new Uri("http://hl7.org/fhir/SearchParameter/ResearchDefinition-context-type"), "code"),
                new SearchParameterStoreComponent(82, 1172, new Uri("http://hl7.org/fhir/SearchParameter/ResearchDefinition-context-quantity"), "value.as(Quantity) | value.as(Range)"),
                new SearchParameterStoreComponent(83, 1173, new Uri("http://hl7.org/fhir/SearchParameter/ResearchDefinition-context-type"), "code"),
                new SearchParameterStoreComponent(84, 1173, new Uri("http://hl7.org/fhir/SearchParameter/ResearchDefinition-context"), "value.as(CodeableConcept)"),
                new SearchParameterStoreComponent(85, 1194, new Uri("http://hl7.org/fhir/SearchParameter/ResearchElementDefinition-context-type"), "code"),
                new SearchParameterStoreComponent(86, 1194, new Uri("http://hl7.org/fhir/SearchParameter/ResearchElementDefinition-context-quantity"), "value.as(Quantity) | value.as(Range)"),
                new SearchParameterStoreComponent(87, 1195, new Uri("http://hl7.org/fhir/SearchParameter/ResearchElementDefinition-context-type"), "code"),
                new SearchParameterStoreComponent(88, 1195, new Uri("http://hl7.org/fhir/SearchParameter/ResearchElementDefinition-context"), "value.as(CodeableConcept)"),
                new SearchParameterStoreComponent(89, 1235, new Uri("http://hl7.org/fhir/SearchParameter/RiskEvidenceSynthesis-context-type"), "code"),
                new SearchParameterStoreComponent(90, 1235, new Uri("http://hl7.org/fhir/SearchParameter/RiskEvidenceSynthesis-context-quantity"), "value.as(Quantity) | value.as(Range)"),
                new SearchParameterStoreComponent(91, 1236, new Uri("http://hl7.org/fhir/SearchParameter/RiskEvidenceSynthesis-context-type"), "code"),
                new SearchParameterStoreComponent(92, 1236, new Uri("http://hl7.org/fhir/SearchParameter/RiskEvidenceSynthesis-context"), "value.as(CodeableConcept)"),
                new SearchParameterStoreComponent(93, 1363, new Uri("http://hl7.org/fhir/SearchParameter/TestScript-context-type"), "code"),
                new SearchParameterStoreComponent(94, 1363, new Uri("http://hl7.org/fhir/SearchParameter/TestScript-context-quantity"), "value.as(Quantity) | value.as(Range)"),
                new SearchParameterStoreComponent(95, 1364, new Uri("http://hl7.org/fhir/SearchParameter/TestScript-context-type"), "code"),
                new SearchParameterStoreComponent(96, 1364, new Uri("http://hl7.org/fhir/SearchParameter/TestScript-context"), "value.as(CodeableConcept)"),
                 
           };
  }
}

