//File code generated using T4 Template found in the project: Abm.Pyro.CodeGeneration
// Last Generated : 7/06/2024 11:18:42 PM

using Abm.Pyro.Domain.Model;
namespace Abm.Pyro.Repository.Seed;

public static class SearchParameterStoreComponentSeed
{
  public static IEnumerable<SearchParameterStoreComponent> Get()
  {
    return new List<SearchParameterStoreComponent>() 
           {
                  new SearchParameterStoreComponent(1, 38, new Uri("http://hl7.org/fhir/SearchParameter/ActivityDefinition-context-type"), "code"),
                new SearchParameterStoreComponent(2, 38, new Uri("http://hl7.org/fhir/SearchParameter/ActivityDefinition-context-quantity"), "value.as(Quantity) | value.as(Range)"),
                new SearchParameterStoreComponent(3, 39, new Uri("http://hl7.org/fhir/SearchParameter/ActivityDefinition-context-type"), "code"),
                new SearchParameterStoreComponent(4, 39, new Uri("http://hl7.org/fhir/SearchParameter/ActivityDefinition-context"), "value.as(CodeableConcept)"),
                new SearchParameterStoreComponent(5, 146, new Uri("http://hl7.org/fhir/SearchParameter/conformance-context-type"), "code"),
                new SearchParameterStoreComponent(6, 146, new Uri("http://hl7.org/fhir/SearchParameter/conformance-context-quantity"), "value.as(Quantity) | value.as(Range)"),
                new SearchParameterStoreComponent(7, 147, new Uri("http://hl7.org/fhir/SearchParameter/conformance-context-type"), "code"),
                new SearchParameterStoreComponent(8, 147, new Uri("http://hl7.org/fhir/SearchParameter/conformance-context"), "value.as(CodeableConcept)"),
                new SearchParameterStoreComponent(9, 200, new Uri("http://hl7.org/fhir/SearchParameter/ChargeItemDefinition-context-type"), "code"),
                new SearchParameterStoreComponent(10, 200, new Uri("http://hl7.org/fhir/SearchParameter/ChargeItemDefinition-context-quantity"), "value.as(Quantity) | value.as(Range)"),
                new SearchParameterStoreComponent(11, 201, new Uri("http://hl7.org/fhir/SearchParameter/ChargeItemDefinition-context-type"), "code"),
                new SearchParameterStoreComponent(12, 201, new Uri("http://hl7.org/fhir/SearchParameter/ChargeItemDefinition-context"), "value.as(CodeableConcept)"),
                new SearchParameterStoreComponent(13, 454, new Uri("http://hl7.org/fhir/SearchParameter/DocumentReference-relatesto"), "code"),
                new SearchParameterStoreComponent(14, 454, new Uri("http://hl7.org/fhir/SearchParameter/DocumentReference-relation"), "target"),
                new SearchParameterStoreComponent(15, 469, new Uri("http://hl7.org/fhir/SearchParameter/EffectEvidenceSynthesis-context-type"), "code"),
                new SearchParameterStoreComponent(16, 469, new Uri("http://hl7.org/fhir/SearchParameter/EffectEvidenceSynthesis-context-quantity"), "value.as(Quantity) | value.as(Range)"),
                new SearchParameterStoreComponent(17, 470, new Uri("http://hl7.org/fhir/SearchParameter/EffectEvidenceSynthesis-context-type"), "code"),
                new SearchParameterStoreComponent(18, 470, new Uri("http://hl7.org/fhir/SearchParameter/EffectEvidenceSynthesis-context"), "value.as(CodeableConcept)"),
                new SearchParameterStoreComponent(19, 528, new Uri("http://hl7.org/fhir/SearchParameter/EventDefinition-context-type"), "code"),
                new SearchParameterStoreComponent(20, 528, new Uri("http://hl7.org/fhir/SearchParameter/EventDefinition-context-quantity"), "value.as(Quantity) | value.as(Range)"),
                new SearchParameterStoreComponent(21, 529, new Uri("http://hl7.org/fhir/SearchParameter/EventDefinition-context-type"), "code"),
                new SearchParameterStoreComponent(22, 529, new Uri("http://hl7.org/fhir/SearchParameter/EventDefinition-context"), "value.as(CodeableConcept)"),
                new SearchParameterStoreComponent(23, 550, new Uri("http://hl7.org/fhir/SearchParameter/Evidence-context-type"), "code"),
                new SearchParameterStoreComponent(24, 550, new Uri("http://hl7.org/fhir/SearchParameter/Evidence-context-quantity"), "value.as(Quantity) | value.as(Range)"),
                new SearchParameterStoreComponent(25, 551, new Uri("http://hl7.org/fhir/SearchParameter/Evidence-context-type"), "code"),
                new SearchParameterStoreComponent(26, 551, new Uri("http://hl7.org/fhir/SearchParameter/Evidence-context"), "value.as(CodeableConcept)"),
                new SearchParameterStoreComponent(27, 572, new Uri("http://hl7.org/fhir/SearchParameter/EvidenceVariable-context-type"), "code"),
                new SearchParameterStoreComponent(28, 572, new Uri("http://hl7.org/fhir/SearchParameter/EvidenceVariable-context-quantity"), "value.as(Quantity) | value.as(Range)"),
                new SearchParameterStoreComponent(29, 573, new Uri("http://hl7.org/fhir/SearchParameter/EvidenceVariable-context-type"), "code"),
                new SearchParameterStoreComponent(30, 573, new Uri("http://hl7.org/fhir/SearchParameter/EvidenceVariable-context"), "value.as(CodeableConcept)"),
                new SearchParameterStoreComponent(31, 585, new Uri("http://hl7.org/fhir/SearchParameter/ExampleScenario-context-type"), "code"),
                new SearchParameterStoreComponent(32, 585, new Uri("http://hl7.org/fhir/SearchParameter/ExampleScenario-context-quantity"), "value.as(Quantity) | value.as(Range)"),
                new SearchParameterStoreComponent(33, 586, new Uri("http://hl7.org/fhir/SearchParameter/ExampleScenario-context-type"), "code"),
                new SearchParameterStoreComponent(34, 586, new Uri("http://hl7.org/fhir/SearchParameter/ExampleScenario-context"), "value.as(CodeableConcept)"),
                new SearchParameterStoreComponent(35, 628, new Uri("http://hl7.org/fhir/SearchParameter/Group-characteristic"), "code"),
                new SearchParameterStoreComponent(36, 628, new Uri("http://hl7.org/fhir/SearchParameter/Group-value"), "value"),
                new SearchParameterStoreComponent(37, 741, new Uri("http://hl7.org/fhir/SearchParameter/Library-context-type"), "code"),
                new SearchParameterStoreComponent(38, 741, new Uri("http://hl7.org/fhir/SearchParameter/Library-context-quantity"), "value.as(Quantity) | value.as(Range)"),
                new SearchParameterStoreComponent(39, 742, new Uri("http://hl7.org/fhir/SearchParameter/Library-context-type"), "code"),
                new SearchParameterStoreComponent(40, 742, new Uri("http://hl7.org/fhir/SearchParameter/Library-context"), "value.as(CodeableConcept)"),
                new SearchParameterStoreComponent(41, 788, new Uri("http://hl7.org/fhir/SearchParameter/Measure-context-type"), "code"),
                new SearchParameterStoreComponent(42, 788, new Uri("http://hl7.org/fhir/SearchParameter/Measure-context-quantity"), "value.as(Quantity) | value.as(Range)"),
                new SearchParameterStoreComponent(43, 789, new Uri("http://hl7.org/fhir/SearchParameter/Measure-context-type"), "code"),
                new SearchParameterStoreComponent(44, 789, new Uri("http://hl7.org/fhir/SearchParameter/Measure-context"), "value.as(CodeableConcept)"),
                new SearchParameterStoreComponent(45, 914, new Uri("http://hl7.org/fhir/SearchParameter/MolecularSequence-chromosome"), "%resource.referenceSeq.chromosome"),
                new SearchParameterStoreComponent(46, 914, new Uri("http://hl7.org/fhir/SearchParameter/MolecularSequence-variant-start"), "start"),
                new SearchParameterStoreComponent(47, 914, new Uri("http://hl7.org/fhir/SearchParameter/MolecularSequence-variant-end"), "end"),
                new SearchParameterStoreComponent(48, 915, new Uri("http://hl7.org/fhir/SearchParameter/MolecularSequence-chromosome"), "chromosome"),
                new SearchParameterStoreComponent(49, 915, new Uri("http://hl7.org/fhir/SearchParameter/MolecularSequence-window-start"), "windowStart"),
                new SearchParameterStoreComponent(50, 915, new Uri("http://hl7.org/fhir/SearchParameter/MolecularSequence-window-end"), "windowEnd"),
                new SearchParameterStoreComponent(51, 916, new Uri("http://hl7.org/fhir/SearchParameter/MolecularSequence-referenceseqid"), "%resource.referenceSeq.referenceSeqId"),
                new SearchParameterStoreComponent(52, 916, new Uri("http://hl7.org/fhir/SearchParameter/MolecularSequence-variant-start"), "start"),
                new SearchParameterStoreComponent(53, 916, new Uri("http://hl7.org/fhir/SearchParameter/MolecularSequence-variant-end"), "end"),
                new SearchParameterStoreComponent(54, 917, new Uri("http://hl7.org/fhir/SearchParameter/MolecularSequence-referenceseqid"), "referenceSeqId"),
                new SearchParameterStoreComponent(55, 917, new Uri("http://hl7.org/fhir/SearchParameter/MolecularSequence-window-start"), "windowStart"),
                new SearchParameterStoreComponent(56, 917, new Uri("http://hl7.org/fhir/SearchParameter/MolecularSequence-window-end"), "windowEnd"),
                new SearchParameterStoreComponent(57, 960, new Uri("http://hl7.org/fhir/SearchParameter/clinical-code"), "code"),
                new SearchParameterStoreComponent(58, 960, new Uri("http://hl7.org/fhir/SearchParameter/Observation-value-concept"), "value.as(CodeableConcept)"),
                new SearchParameterStoreComponent(59, 961, new Uri("http://hl7.org/fhir/SearchParameter/clinical-code"), "code"),
                new SearchParameterStoreComponent(60, 961, new Uri("http://hl7.org/fhir/SearchParameter/Observation-value-date"), "value.as(DateTime) | value.as(Period)"),
                new SearchParameterStoreComponent(61, 962, new Uri("http://hl7.org/fhir/SearchParameter/clinical-code"), "code"),
                new SearchParameterStoreComponent(62, 962, new Uri("http://hl7.org/fhir/SearchParameter/Observation-value-quantity"), "value.as(Quantity)"),
                new SearchParameterStoreComponent(63, 963, new Uri("http://hl7.org/fhir/SearchParameter/clinical-code"), "code"),
                new SearchParameterStoreComponent(64, 963, new Uri("http://hl7.org/fhir/SearchParameter/Observation-value-string"), "value.as(string)"),
                new SearchParameterStoreComponent(65, 964, new Uri("http://hl7.org/fhir/SearchParameter/Observation-combo-code"), "code"),
                new SearchParameterStoreComponent(66, 964, new Uri("http://hl7.org/fhir/SearchParameter/Observation-combo-value-concept"), "value.as(CodeableConcept)"),
                new SearchParameterStoreComponent(67, 965, new Uri("http://hl7.org/fhir/SearchParameter/Observation-combo-code"), "code"),
                new SearchParameterStoreComponent(68, 965, new Uri("http://hl7.org/fhir/SearchParameter/Observation-combo-value-quantity"), "value.as(Quantity)"),
                new SearchParameterStoreComponent(69, 966, new Uri("http://hl7.org/fhir/SearchParameter/Observation-component-code"), "code"),
                new SearchParameterStoreComponent(70, 966, new Uri("http://hl7.org/fhir/SearchParameter/Observation-component-value-concept"), "value.as(CodeableConcept)"),
                new SearchParameterStoreComponent(71, 967, new Uri("http://hl7.org/fhir/SearchParameter/Observation-component-code"), "code"),
                new SearchParameterStoreComponent(72, 967, new Uri("http://hl7.org/fhir/SearchParameter/Observation-component-value-quantity"), "value.as(Quantity)"),
                new SearchParameterStoreComponent(73, 1070, new Uri("http://hl7.org/fhir/SearchParameter/PlanDefinition-context-type"), "code"),
                new SearchParameterStoreComponent(74, 1070, new Uri("http://hl7.org/fhir/SearchParameter/PlanDefinition-context-quantity"), "value.as(Quantity) | value.as(Range)"),
                new SearchParameterStoreComponent(75, 1071, new Uri("http://hl7.org/fhir/SearchParameter/PlanDefinition-context-type"), "code"),
                new SearchParameterStoreComponent(76, 1071, new Uri("http://hl7.org/fhir/SearchParameter/PlanDefinition-context"), "value.as(CodeableConcept)"),
                new SearchParameterStoreComponent(77, 1124, new Uri("http://hl7.org/fhir/SearchParameter/Questionnaire-context-type"), "code"),
                new SearchParameterStoreComponent(78, 1124, new Uri("http://hl7.org/fhir/SearchParameter/Questionnaire-context-quantity"), "value.as(Quantity) | value.as(Range)"),
                new SearchParameterStoreComponent(79, 1125, new Uri("http://hl7.org/fhir/SearchParameter/Questionnaire-context-type"), "code"),
                new SearchParameterStoreComponent(80, 1125, new Uri("http://hl7.org/fhir/SearchParameter/Questionnaire-context"), "value.as(CodeableConcept)"),
                new SearchParameterStoreComponent(81, 1176, new Uri("http://hl7.org/fhir/SearchParameter/ResearchDefinition-context-type"), "code"),
                new SearchParameterStoreComponent(82, 1176, new Uri("http://hl7.org/fhir/SearchParameter/ResearchDefinition-context-quantity"), "value.as(Quantity) | value.as(Range)"),
                new SearchParameterStoreComponent(83, 1177, new Uri("http://hl7.org/fhir/SearchParameter/ResearchDefinition-context-type"), "code"),
                new SearchParameterStoreComponent(84, 1177, new Uri("http://hl7.org/fhir/SearchParameter/ResearchDefinition-context"), "value.as(CodeableConcept)"),
                new SearchParameterStoreComponent(85, 1198, new Uri("http://hl7.org/fhir/SearchParameter/ResearchElementDefinition-context-type"), "code"),
                new SearchParameterStoreComponent(86, 1198, new Uri("http://hl7.org/fhir/SearchParameter/ResearchElementDefinition-context-quantity"), "value.as(Quantity) | value.as(Range)"),
                new SearchParameterStoreComponent(87, 1199, new Uri("http://hl7.org/fhir/SearchParameter/ResearchElementDefinition-context-type"), "code"),
                new SearchParameterStoreComponent(88, 1199, new Uri("http://hl7.org/fhir/SearchParameter/ResearchElementDefinition-context"), "value.as(CodeableConcept)"),
                new SearchParameterStoreComponent(89, 1239, new Uri("http://hl7.org/fhir/SearchParameter/RiskEvidenceSynthesis-context-type"), "code"),
                new SearchParameterStoreComponent(90, 1239, new Uri("http://hl7.org/fhir/SearchParameter/RiskEvidenceSynthesis-context-quantity"), "value.as(Quantity) | value.as(Range)"),
                new SearchParameterStoreComponent(91, 1240, new Uri("http://hl7.org/fhir/SearchParameter/RiskEvidenceSynthesis-context-type"), "code"),
                new SearchParameterStoreComponent(92, 1240, new Uri("http://hl7.org/fhir/SearchParameter/RiskEvidenceSynthesis-context"), "value.as(CodeableConcept)"),
                new SearchParameterStoreComponent(93, 1367, new Uri("http://hl7.org/fhir/SearchParameter/TestScript-context-type"), "code"),
                new SearchParameterStoreComponent(94, 1367, new Uri("http://hl7.org/fhir/SearchParameter/TestScript-context-quantity"), "value.as(Quantity) | value.as(Range)"),
                new SearchParameterStoreComponent(95, 1368, new Uri("http://hl7.org/fhir/SearchParameter/TestScript-context-type"), "code"),
                new SearchParameterStoreComponent(96, 1368, new Uri("http://hl7.org/fhir/SearchParameter/TestScript-context"), "value.as(CodeableConcept)"),
                 
           };
  }
}

