<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>13</LangVersion>
        <UserSecretsId>08007212-d74d-4291-9832-1212af5fa9aa</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="LinqKit.Microsoft.EntityFrameworkCore" Version="9.0.8" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.1" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.1">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.1" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.1">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="9.0.1" />
      <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="9.0.1" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.1" />
      <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="9.0.1" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Microsoft.Extensions.Logging.Abstractions">
        <HintPath>C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\6.0.14\Microsoft.Extensions.Logging.Abstractions.dll</HintPath>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Abm.Pyro.Domain\Abm.Pyro.Domain.csproj" />
    </ItemGroup>



</Project>
