using Abm.Pyro.Domain.Attributes;

namespace Abm.Pyro.Domain.Enums;

public enum BundleType 
{
      /// <summary>
      /// The bundle is a document. The first resource is a Composition.
      /// (system: http://hl7.org/fhir/bundle-type)
      /// </summary>
      [EnumInfo("document", "Document")]
      Document,
      /// <summary>
      /// The bundle is a message. The first resource is a MessageHeader.
      /// (system: http://hl7.org/fhir/bundle-type)
      /// </summary>
      [EnumInfo("message", "Message")]
      Message,
      /// <summary>
      /// The bundle is a transaction - intended to be processed by a server as an atomic commit.
      /// (system: http://hl7.org/fhir/bundle-type)
      /// </summary>
      [EnumInfo("transaction", "Transaction")]
      Transaction,
      /// <summary>
      /// The bundle is a transaction response. Because the response is a transaction response, the transaction has succeeded, and all responses are error free.
      /// (system: http://hl7.org/fhir/bundle-type)
      /// </summary>
      [EnumInfo("transaction-response", "Transaction Response")]
      TransactionResponse,
      /// <summary>
      /// The bundle is a set of actions - intended to be processed by a server as a group of independent actions.
      /// (system: http://hl7.org/fhir/bundle-type)
      /// </summary>
      [EnumInfo("batch", "Batch")]
      Batch,
      /// <summary>
      /// The bundle is a batch response. Note that as a batch, some responses may indicate failure and others success.
      /// (system: http://hl7.org/fhir/bundle-type)
      /// </summary>
      [EnumInfo("batch-response", "Batch Response")]
      BatchResponse,
      /// <summary>
      /// The bundle is a list of resources from a history interaction on a server.
      /// (system: http://hl7.org/fhir/bundle-type)
      /// </summary>
      [EnumInfo("history", "History List")]
      History,
      /// <summary>
      /// The bundle is a list of resources returned as a result of a search/query interaction, operation, or message.
      /// (system: http://hl7.org/fhir/bundle-type)
      /// </summary>
      [EnumInfo("searchset", "Search Results")]
      Searchset,
      /// <summary>
      /// The bundle is a set of resources collected into a single package for ease of distribution that imposes no processing obligations or behavioral rules beyond persistence.
      /// (system: http://hl7.org/fhir/bundle-type)
      /// </summary>
      [EnumInfo("collection", "Collection")]
      Collection,
      /// <summary>
      /// The bundle has been generated by a Subscription to communicate information to a client.
      /// (system: http://hl7.org/fhir/bundle-type)
      /// </summary>
      [EnumInfo("subscription-notification", "Subscription Notification")]
      SubscriptionNotification,
  
};
