//File code generated using T4 Template found in the project: Abm.Pyro.CodeGeneration
// Last Generated : 7/06/2024 11:52:30 PM
using Abm.Pyro.Domain.Attributes;
namespace Abm.Pyro.Domain.Enums;

public enum FhirResourceTypeId
{
    [EnumInfo("Resource", "Resource" )]
    Resource = 1,         
    [EnumInfo("DomainResource", "DomainResource" )]
    DomainResource = 2,         
    [EnumInfo("Account", "Account" )]
    Account = 3,         
    [EnumInfo("ActivityDefinition", "ActivityDefinition" )]
    ActivityDefinition = 4,         
    [EnumInfo("AdverseEvent", "AdverseEvent" )]
    AdverseEvent = 5,         
    [EnumInfo("AllergyIntolerance", "AllergyIntolerance" )]
    AllergyIntolerance = 6,         
    [EnumInfo("Appointment", "Appointment" )]
    Appointment = 7,         
    [EnumInfo("AppointmentResponse", "AppointmentResponse" )]
    AppointmentResponse = 8,         
    [EnumInfo("AuditEvent", "AuditEvent" )]
    AuditEvent = 9,         
    [EnumInfo("Basic", "Basic" )]
    Basic = 10,         
    [EnumInfo("Binary", "Binary" )]
    Binary = 11,         
    [EnumInfo("BiologicallyDerivedProduct", "BiologicallyDerivedProduct" )]
    BiologicallyDerivedProduct = 12,         
    [EnumInfo("BodyStructure", "BodyStructure" )]
    BodyStructure = 13,         
    [EnumInfo("Bundle", "Bundle" )]
    Bundle = 14,         
    [EnumInfo("CapabilityStatement", "CapabilityStatement" )]
    CapabilityStatement = 15,         
    [EnumInfo("CarePlan", "CarePlan" )]
    CarePlan = 16,         
    [EnumInfo("CareTeam", "CareTeam" )]
    CareTeam = 17,         
    [EnumInfo("CatalogEntry", "CatalogEntry" )]
    CatalogEntry = 18,         
    [EnumInfo("ChargeItem", "ChargeItem" )]
    ChargeItem = 19,         
    [EnumInfo("ChargeItemDefinition", "ChargeItemDefinition" )]
    ChargeItemDefinition = 20,         
    [EnumInfo("Claim", "Claim" )]
    Claim = 21,         
    [EnumInfo("ClaimResponse", "ClaimResponse" )]
    ClaimResponse = 22,         
    [EnumInfo("ClinicalImpression", "ClinicalImpression" )]
    ClinicalImpression = 23,         
    [EnumInfo("CodeSystem", "CodeSystem" )]
    CodeSystem = 24,         
    [EnumInfo("Communication", "Communication" )]
    Communication = 25,         
    [EnumInfo("CommunicationRequest", "CommunicationRequest" )]
    CommunicationRequest = 26,         
    [EnumInfo("CompartmentDefinition", "CompartmentDefinition" )]
    CompartmentDefinition = 27,         
    [EnumInfo("Composition", "Composition" )]
    Composition = 28,         
    [EnumInfo("ConceptMap", "ConceptMap" )]
    ConceptMap = 29,         
    [EnumInfo("Condition", "Condition" )]
    Condition = 30,         
    [EnumInfo("Consent", "Consent" )]
    Consent = 31,         
    [EnumInfo("Contract", "Contract" )]
    Contract = 32,         
    [EnumInfo("Coverage", "Coverage" )]
    Coverage = 33,         
    [EnumInfo("CoverageEligibilityRequest", "CoverageEligibilityRequest" )]
    CoverageEligibilityRequest = 34,         
    [EnumInfo("CoverageEligibilityResponse", "CoverageEligibilityResponse" )]
    CoverageEligibilityResponse = 35,         
    [EnumInfo("DetectedIssue", "DetectedIssue" )]
    DetectedIssue = 36,         
    [EnumInfo("Device", "Device" )]
    Device = 37,         
    [EnumInfo("DeviceDefinition", "DeviceDefinition" )]
    DeviceDefinition = 38,         
    [EnumInfo("DeviceMetric", "DeviceMetric" )]
    DeviceMetric = 39,         
    [EnumInfo("DeviceRequest", "DeviceRequest" )]
    DeviceRequest = 40,         
    [EnumInfo("DeviceUseStatement", "DeviceUseStatement" )]
    DeviceUseStatement = 41,         
    [EnumInfo("DiagnosticReport", "DiagnosticReport" )]
    DiagnosticReport = 42,         
    [EnumInfo("DocumentManifest", "DocumentManifest" )]
    DocumentManifest = 43,         
    [EnumInfo("DocumentReference", "DocumentReference" )]
    DocumentReference = 44,         
    [EnumInfo("EffectEvidenceSynthesis", "EffectEvidenceSynthesis" )]
    EffectEvidenceSynthesis = 45,         
    [EnumInfo("Encounter", "Encounter" )]
    Encounter = 46,         
    [EnumInfo("Endpoint", "Endpoint" )]
    Endpoint = 47,         
    [EnumInfo("EnrollmentRequest", "EnrollmentRequest" )]
    EnrollmentRequest = 48,         
    [EnumInfo("EnrollmentResponse", "EnrollmentResponse" )]
    EnrollmentResponse = 49,         
    [EnumInfo("EpisodeOfCare", "EpisodeOfCare" )]
    EpisodeOfCare = 50,         
    [EnumInfo("EventDefinition", "EventDefinition" )]
    EventDefinition = 51,         
    [EnumInfo("Evidence", "Evidence" )]
    Evidence = 52,         
    [EnumInfo("EvidenceVariable", "EvidenceVariable" )]
    EvidenceVariable = 53,         
    [EnumInfo("ExampleScenario", "ExampleScenario" )]
    ExampleScenario = 54,         
    [EnumInfo("ExplanationOfBenefit", "ExplanationOfBenefit" )]
    ExplanationOfBenefit = 55,         
    [EnumInfo("FamilyMemberHistory", "FamilyMemberHistory" )]
    FamilyMemberHistory = 56,         
    [EnumInfo("Flag", "Flag" )]
    Flag = 57,         
    [EnumInfo("Goal", "Goal" )]
    Goal = 58,         
    [EnumInfo("GraphDefinition", "GraphDefinition" )]
    GraphDefinition = 59,         
    [EnumInfo("Group", "Group" )]
    Group = 60,         
    [EnumInfo("GuidanceResponse", "GuidanceResponse" )]
    GuidanceResponse = 61,         
    [EnumInfo("HealthcareService", "HealthcareService" )]
    HealthcareService = 62,         
    [EnumInfo("ImagingStudy", "ImagingStudy" )]
    ImagingStudy = 63,         
    [EnumInfo("Immunization", "Immunization" )]
    Immunization = 64,         
    [EnumInfo("ImmunizationEvaluation", "ImmunizationEvaluation" )]
    ImmunizationEvaluation = 65,         
    [EnumInfo("ImmunizationRecommendation", "ImmunizationRecommendation" )]
    ImmunizationRecommendation = 66,         
    [EnumInfo("ImplementationGuide", "ImplementationGuide" )]
    ImplementationGuide = 67,         
    [EnumInfo("InsurancePlan", "InsurancePlan" )]
    InsurancePlan = 68,         
    [EnumInfo("Invoice", "Invoice" )]
    Invoice = 69,         
    [EnumInfo("Library", "Library" )]
    Library = 70,         
    [EnumInfo("Linkage", "Linkage" )]
    Linkage = 71,         
    [EnumInfo("List", "List" )]
    List = 72,         
    [EnumInfo("Location", "Location" )]
    Location = 73,         
    [EnumInfo("Measure", "Measure" )]
    Measure = 74,         
    [EnumInfo("MeasureReport", "MeasureReport" )]
    MeasureReport = 75,         
    [EnumInfo("Media", "Media" )]
    Media = 76,         
    [EnumInfo("Medication", "Medication" )]
    Medication = 77,         
    [EnumInfo("MedicationAdministration", "MedicationAdministration" )]
    MedicationAdministration = 78,         
    [EnumInfo("MedicationDispense", "MedicationDispense" )]
    MedicationDispense = 79,         
    [EnumInfo("MedicationKnowledge", "MedicationKnowledge" )]
    MedicationKnowledge = 80,         
    [EnumInfo("MedicationRequest", "MedicationRequest" )]
    MedicationRequest = 81,         
    [EnumInfo("MedicationStatement", "MedicationStatement" )]
    MedicationStatement = 82,         
    [EnumInfo("MedicinalProduct", "MedicinalProduct" )]
    MedicinalProduct = 83,         
    [EnumInfo("MedicinalProductAuthorization", "MedicinalProductAuthorization" )]
    MedicinalProductAuthorization = 84,         
    [EnumInfo("MedicinalProductContraindication", "MedicinalProductContraindication" )]
    MedicinalProductContraindication = 85,         
    [EnumInfo("MedicinalProductIndication", "MedicinalProductIndication" )]
    MedicinalProductIndication = 86,         
    [EnumInfo("MedicinalProductIngredient", "MedicinalProductIngredient" )]
    MedicinalProductIngredient = 87,         
    [EnumInfo("MedicinalProductInteraction", "MedicinalProductInteraction" )]
    MedicinalProductInteraction = 88,         
    [EnumInfo("MedicinalProductManufactured", "MedicinalProductManufactured" )]
    MedicinalProductManufactured = 89,         
    [EnumInfo("MedicinalProductPackaged", "MedicinalProductPackaged" )]
    MedicinalProductPackaged = 90,         
    [EnumInfo("MedicinalProductPharmaceutical", "MedicinalProductPharmaceutical" )]
    MedicinalProductPharmaceutical = 91,         
    [EnumInfo("MedicinalProductUndesirableEffect", "MedicinalProductUndesirableEffect" )]
    MedicinalProductUndesirableEffect = 92,         
    [EnumInfo("MessageDefinition", "MessageDefinition" )]
    MessageDefinition = 93,         
    [EnumInfo("MessageHeader", "MessageHeader" )]
    MessageHeader = 94,         
    [EnumInfo("MolecularSequence", "MolecularSequence" )]
    MolecularSequence = 95,         
    [EnumInfo("NamingSystem", "NamingSystem" )]
    NamingSystem = 96,         
    [EnumInfo("NutritionOrder", "NutritionOrder" )]
    NutritionOrder = 97,         
    [EnumInfo("Observation", "Observation" )]
    Observation = 98,         
    [EnumInfo("ObservationDefinition", "ObservationDefinition" )]
    ObservationDefinition = 99,         
    [EnumInfo("OperationDefinition", "OperationDefinition" )]
    OperationDefinition = 100,         
    [EnumInfo("OperationOutcome", "OperationOutcome" )]
    OperationOutcome = 101,         
    [EnumInfo("Organization", "Organization" )]
    Organization = 102,         
    [EnumInfo("OrganizationAffiliation", "OrganizationAffiliation" )]
    OrganizationAffiliation = 103,         
    [EnumInfo("Parameters", "Parameters" )]
    Parameters = 104,         
    [EnumInfo("Patient", "Patient" )]
    Patient = 105,         
    [EnumInfo("PaymentNotice", "PaymentNotice" )]
    PaymentNotice = 106,         
    [EnumInfo("PaymentReconciliation", "PaymentReconciliation" )]
    PaymentReconciliation = 107,         
    [EnumInfo("Person", "Person" )]
    Person = 108,         
    [EnumInfo("PlanDefinition", "PlanDefinition" )]
    PlanDefinition = 109,         
    [EnumInfo("Practitioner", "Practitioner" )]
    Practitioner = 110,         
    [EnumInfo("PractitionerRole", "PractitionerRole" )]
    PractitionerRole = 111,         
    [EnumInfo("Procedure", "Procedure" )]
    Procedure = 112,         
    [EnumInfo("Provenance", "Provenance" )]
    Provenance = 113,         
    [EnumInfo("Questionnaire", "Questionnaire" )]
    Questionnaire = 114,         
    [EnumInfo("QuestionnaireResponse", "QuestionnaireResponse" )]
    QuestionnaireResponse = 115,         
    [EnumInfo("RelatedPerson", "RelatedPerson" )]
    RelatedPerson = 116,         
    [EnumInfo("RequestGroup", "RequestGroup" )]
    RequestGroup = 117,         
    [EnumInfo("ResearchDefinition", "ResearchDefinition" )]
    ResearchDefinition = 118,         
    [EnumInfo("ResearchElementDefinition", "ResearchElementDefinition" )]
    ResearchElementDefinition = 119,         
    [EnumInfo("ResearchStudy", "ResearchStudy" )]
    ResearchStudy = 120,         
    [EnumInfo("ResearchSubject", "ResearchSubject" )]
    ResearchSubject = 121,         
    [EnumInfo("RiskAssessment", "RiskAssessment" )]
    RiskAssessment = 122,         
    [EnumInfo("RiskEvidenceSynthesis", "RiskEvidenceSynthesis" )]
    RiskEvidenceSynthesis = 123,         
    [EnumInfo("Schedule", "Schedule" )]
    Schedule = 124,         
    [EnumInfo("SearchParameter", "SearchParameter" )]
    SearchParameter = 125,         
    [EnumInfo("ServiceRequest", "ServiceRequest" )]
    ServiceRequest = 126,         
    [EnumInfo("Slot", "Slot" )]
    Slot = 127,         
    [EnumInfo("Specimen", "Specimen" )]
    Specimen = 128,         
    [EnumInfo("SpecimenDefinition", "SpecimenDefinition" )]
    SpecimenDefinition = 129,         
    [EnumInfo("StructureDefinition", "StructureDefinition" )]
    StructureDefinition = 130,         
    [EnumInfo("StructureMap", "StructureMap" )]
    StructureMap = 131,         
    [EnumInfo("Subscription", "Subscription" )]
    Subscription = 132,         
    [EnumInfo("Substance", "Substance" )]
    Substance = 133,         
    [EnumInfo("SubstanceNucleicAcid", "SubstanceNucleicAcid" )]
    SubstanceNucleicAcid = 134,         
    [EnumInfo("SubstancePolymer", "SubstancePolymer" )]
    SubstancePolymer = 135,         
    [EnumInfo("SubstanceProtein", "SubstanceProtein" )]
    SubstanceProtein = 136,         
    [EnumInfo("SubstanceReferenceInformation", "SubstanceReferenceInformation" )]
    SubstanceReferenceInformation = 137,         
    [EnumInfo("SubstanceSourceMaterial", "SubstanceSourceMaterial" )]
    SubstanceSourceMaterial = 138,         
    [EnumInfo("SubstanceSpecification", "SubstanceSpecification" )]
    SubstanceSpecification = 139,         
    [EnumInfo("SupplyDelivery", "SupplyDelivery" )]
    SupplyDelivery = 140,         
    [EnumInfo("SupplyRequest", "SupplyRequest" )]
    SupplyRequest = 141,         
    [EnumInfo("Task", "Task" )]
    Task = 142,         
    [EnumInfo("TerminologyCapabilities", "TerminologyCapabilities" )]
    TerminologyCapabilities = 143,         
    [EnumInfo("TestReport", "TestReport" )]
    TestReport = 144,         
    [EnumInfo("TestScript", "TestScript" )]
    TestScript = 145,         
    [EnumInfo("ValueSet", "ValueSet" )]
    ValueSet = 146,         
    [EnumInfo("VerificationResult", "VerificationResult" )]
    VerificationResult = 147,         
    [EnumInfo("VisionPrescription", "VisionPrescription" )]
    VisionPrescription = 148,         
                   
}

